### ISSUE TITLE
FSharp.Data.SqlClient demo

### ISSUE THREAD

**Issue by brettrowberry** [JordanMarr/SsdtParser#1]
I am very excited about the goal of this project. I would love to see a full demo for SQL Server using
https://fsprojects.github.io/FSharp.Data.SqlClient/ or
https://fsprojects.github.io/SQLProvider/

**Comment by JordanMarr** [comment]
I've already started on SQLProvider: https://github.com/fsprojects/SQLProvider/issues/698

FSharp.Data.SqlClient is an _excellent_ candidate since it doesn't have a caching mechanism. I will try for both!

As for this repo, today I will be creating a new branch to experiment with Microsoft.SqlServer.Management.SqlParser, since that will be a better platform for real-world use in SQLProvider or FSharp.Data.SqlClient.

**Comment by JordanMarr** [comment]
With regards to FSharp.Data.SqlClient, it just occurred to me that in addition to requiring a SQL Connection to list columns and table names, FSharp.Data.SqlClient probably sends each individual query to SQL Server in order to check that it's valid.
If that's the case, then even if it could derive a schema from SSDT, it still would need an active connection to validate queries.

**Comment by brettrowberry** [comment]
Cool, whatever you think is best! Thanks for your efforts!

**Comment by brettrowberry** [comment]
I think this is old enough. Thanks for your cool project!

**Comment by JordanMarr** [comment]
Just curious, but did the SSDT provider in SQLProvider work for your scenario?

**Comment by brettrowberry** [comment]
I changed companies and am now doing Clojure and PostgreSQL and never got around to testing this!

**Comment by JordanMarr** [comment]
That sounds like a fun job. Congrats! :)
